name: credit_card_manager_beta
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  flutter_credit_card: ^3.0.1
  flutter_native_splash: ^2.1.1
  charts_flutter: ^0.12.0
  favorite_button: ^0.0.4
  sqflite: ^2.0.2
  intl: ^0.17.0
  get: ^4.6.1
  flutter_svg: ^1.0.3
  flutter_toggle_tab: ^1.1.7
  pie_chart: ^5.1.0
  syncfusion_flutter_datepicker: ^19.4.52
  path_provider: ^2.0.9

dev_dependencies:

  flutter_launcher_icons: ^0.9.2

  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
flutter_native_splash:
  color: "#6699cc"
  image: assets/card-logo.png
# The following section is specific to Flutter.




flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/card-logo.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/export/Ellipse center.svg
    - assets/export/Scroll Group 1.svg
    - assets/export/Scroll Group 2.svg
    - assets/export/Main Box.svg
    - assets/export/logo final.png
    - assets/export/logo heading.png
    - assets/export/simple_logo.png
    - assets/export/Union 1.png
    - assets/export/clipboard.png
    - assets/export/contract.png

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
        # - asset: fonts/Schyler-Italic.ttf
        #   style: italic
    - family: Custom_icons
      fonts:
        - asset: assets/fonts/Custom_icons.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
